/*
	This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU Lesser General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Lesser General Public License for more details.

    You should have received a copy of the GNU Lesser General Public License
    along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

#pragma once

#include "patch_access_key.hpp"
#include "patch_exo_sceneidx.hpp"
#include "patch_exo_trackparam.hpp"
#include "patch_exo_trackminusval.hpp"
#include "patch_tra_aviutlfilter.hpp"
#include "patch_exo_aviutlfilter.hpp"
#include "patch_exo_specialcolorconv.hpp"
#include "patch_lua.hpp"
#include "patch_console.hpp"
#include "patch_exception_log.hpp"
#include "patch_aviutl_wndproc_override.hpp"
#include "patch_sysinfo_write.hpp"
#include "patch_splash.hpp"
#include "patch_scroll_objdlg.hpp"
#include "patch_text_op_size.hpp"
#include "patch_ignore_media_param_reset.hpp"
#include "patch_susie_load.hpp"
#include "patch_alpha_bg.hpp"
#include "patch_theme_cc.hpp"
#include "patch_helpful_msgbox.hpp"
#include "patch_fast_setting_dialog.hpp"
#include "patch_fast_exeditwindow.hpp"
#include "patch_exeditwindow_sizing.hpp"
#include "patch_setting_dialog_wndproc_override.hpp"
#include "patch_undo.hpp"
#include "patch_fast_getputpixeldata.hpp"
#include "patch_fast_polartransform.hpp"
#include "patch_fast_displacementmap.hpp"
#include "patch_fast_radiationalblur.hpp"
#include "patch_fast_flash.hpp"
#include "patch_fast_lensblur.hpp"
#include "patch_font_dialog.hpp"
#include "patch_setting_dialog_move.hpp"
#include "patch_redo.hpp"
#include "patch_fast.hpp"
#include "patch_fast_cl.hpp"
#include "patch_lua_getvalueex.hpp"
#include "patch_lua_rand.hpp"
#include "patch_lua_randex.hpp"
#include "patch_fast_text.hpp"
#include "patch_fast_create_figure.hpp"
#include "patch_obj_lensblur.hpp"
#include "patch_obj_noise.hpp"
#include "patch_setting_dialog_excolorconfig.hpp"
#include "patch_fast_border.hpp"
#include "patch_fast_directionalblur.hpp"
#include "patch_rclickmenu_split.hpp"
#include "patch_rclickmenu_delete.hpp"
#include "patch_tra_change_drawfilter.hpp"
#include "patch_tra_specified_speed.hpp"
#include "patch_blend.hpp"
#include "patch_failed_sjis_msgbox.hpp"
#include "patch_obj_colorcorrection.hpp"
#include "patch_aup_scene_setting.hpp"
#include "patch_exo_fold_gui.hpp"
#include "patch_colorpalette_cache.hpp"
#include "patch_add_extension.hpp"
#include "patch_obj_specialcolorconv.hpp"
#include "patch_dialog_new_file.hpp"
#include "patch_exo_midpt_and_tra.hpp"
#include "patch_fileinfo.hpp"
#include "patch_playback_speed.hpp"
#include "patch_fast_glow.hpp"
#include "patch_obj_glow.hpp"
#include "patch_setting_new_project.hpp"
#include "patch_aup_layer_setting.hpp"
#include "patch_failed_file_drop.hpp"
#include "patch_failed_longer_path.hpp"
#include "patch_obj_imageloop.hpp"
#include "patch_scene_cache.hpp"
#include "patch_script_sort.hpp"
#include "patch_warning_duplicate_plugins.hpp"
#include "patch_shared_cache.hpp"
#include "patch_rendering.hpp"
#include "patch_yc_rgb_cvt.hpp"
#include "patch_group_camera_scene.hpp"
